name: github.com/leleliu008 -> gitee.com/fpliu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          git config --global user.name  leleliu008
          git config --global user.email leleliu008@gmail.com

          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat > ~/.ssh/config <<-EOF
          Host *
              StrictHostKeyChecking no
          EOF

          while read repo
          do
              case $repo in
                ctags|hexdump|maven-repo)
                  continue
                *)
                  git clone --bare https://github.com/leleliu008/$repo.git
                  git -C $repo.git push --mirror git@gitee.com:fpliu/$repo.git
              esac
          done < github-leleliu008-repos.txt
